# Generated by Django 3.2.18 on 2023-05-04 01:50

from django.db import migrations, models
import group.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public_view', models.BooleanField(default=False)),
                ('is_public_join', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_email_validated', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=group.models.get_groups_image_name)),
                ('db_region', models.CharField(blank=True, choices=[('groups_ind', 'groups_ind'), ('groups_us', 'groups_us'), ('groups_eu', 'groups_eu'), ('groups_africa', 'groups_africa'), ('groups_china', 'groups_china')], max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
