# Generated by Django 3.2.18 on 2023-05-04 01:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('role_description', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('post_as_group', models.BooleanField(default=False)),
                ('manage_members', models.BooleanField(default=False)),
                ('manage_content', models.BooleanField(default=False)),
                ('manage_metadata', models.BooleanField(default=False)),
                ('can_post', models.BooleanField(default=True)),
                ('manage_roles', models.BooleanField(default=False)),
                ('reply_to_authors', models.BooleanField(default=True)),
                ('attach_files', models.BooleanField(default=True)),
                ('view_member_email_addresses', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='group.group')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role_name', 'group'), name='unique_role_name'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default', 'group'), name='unique_default_role'),
        ),
    ]
