# Generated by Django 3.2.18 on 2023-05-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='db_region',
            field=models.CharField(blank=True, choices=[], max_length=255, null=True),
        ),
    ]
